services:
  - type: web
    name: hisabbadi
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
