services:
  - type: web
    name: hisabbadi
    runtime: static
    plan: free
    buildCommand: npm ci && npm run build
    staticPublishPath: out
    envVars:
      - key: NODE_VERSION
        value: 20
